## Super washing machine
You have n super washing machines on a line. Initially, each washing machine has some dresses or is empty.

For each move, you could choose any m (1 ≤ m ≤ n) washing machines, and pass one dress of each washing machine to one of its adjacent washing machines at the same time .

Given an integer array representing the number of dresses in each washing machine from left to right on the line, you should find the minimum number of moves to make all the washing machines have the same number of dresses. If it is not possible to do it, return -1

In [45]:
array=[0,2,7,8,4,3]

In [138]:
# find the min flux for one array
def find_min_cut(array):
    n=len(array)
    import numpy as np
    array=np.array(array)
    total_move=0
    if n==1 or n==0:
        print('done_done!')
        return array
    
    if sum(array)%n:
        print('It is impossible!')
    else: 
        m=sum(array)/n
        final_sum=[]
        final_sum_split=0
        for i in range(n):
            final_sum_split +=m
            final_sum.append(final_sum_split)

        split_sum=0
        first_split=[]
        for i in range(n):
            split_sum+= array[i]
            first_split.append(split_sum)

        print (first_split,final_sum)

        diff_array= [i - k for i, k in zip(first_split, final_sum)]
        print(diff_array)

        import numpy as np
        diff_array=np.array(diff_array)

        if np.all(diff_array==0):
            print('done_done')
            return array
        move_index=np.argmin(abs(diff_array[:-1]))
        first_move= diff_array[move_index]

        array[move_index]=array[move_index]-first_move

        array[move_index +1]=array[move_index+1]+first_move

        new_array1=array[:move_index+1]

        new_array2=array[move_index+1:]

        diff_array[:move_index+1]

        print(first_move,new_array1,new_array2,diff_array[:move_index+1])

        #total_move+= abs(diff_array[:-1])
        return new_array1,new_array2,abs(first_move)


In [48]:
arr, _, _ = find_min_cut(array)

[0, 2, 9, 17, 21, 24] [4.0, 8.0, 12.0, 16.0, 20.0, 24.0]
[-4.0, -6.0, -3.0, 1.0, 1.0, 0.0]
1.0 [0 2 7 7] [5 3] [-4. -6. -3.  1.]


In [139]:
#find the min cut form all arrays and track the total number
def find_min_cut_recursive(arr, x, move_No=0):
    if len(arr)==x: #check if buckets are all even
            return (move_No,arr)
    
    total_aar=[]
    for array in arr:
        n=len(array)
        import numpy as np
        array=np.array(array)
        total_move=0
        if sum(array)%n: #if it's dividable
            print('It is impossible!')
            return -1
        if n==1 or n==0: #check if one bucket reach the minimal number
            print('len_1_done_done!')
            total_aar.append(array)
            continue        
         
        m=sum(array)/n
        final_sum=[] #calculate accumulative actual bucket number
        final_sum_split=0
        for i in range(n):
            final_sum_split +=m
            final_sum.append(final_sum_split)

        split_sum=0 #calculate accumulative expected bucket number
        first_split=[]
        for i in range(n):
            split_sum+= array[i]
            first_split.append(split_sum)
            
        #calculate different expected value
        diff_array= [i - k for i, k in zip(first_split, final_sum)]
        import numpy as np
        diff_array=np.array(diff_array)

        if np.all(diff_array==0):
            print('even_done_done')
            total_aar.append(array)
            continue
        # find the min flux, make the difference and split into 2 arrays
        move_index=np.argmin(abs(diff_array[:-1]))
        first_move= diff_array[move_index]
        
        array[move_index]=array[move_index]-first_move
        array[move_index +1]=array[move_index+1]+first_move

        new_array1=array[:move_index+1]
        total_aar.append(new_array1)

        new_array2=array[move_index+1:]
        total_aar.append(new_array2)

        move_No+= abs(first_move)
        print("total move:", move_No)
        print("this move:",first_move)
        print(new_array1,new_array2)
        
        if len(total_aar)==x:
            print(move_No,total_aar)
            break
            #total_move+= abs(diff_array[:-1])
    return find_min_cut_recursive(total_aar,x,move_No)


In [140]:
find_min_cut_recursive([[8,0,1,5,8,6,0]], 7, move_No=0)

total move: 0.0
this move: 0.0
[8 0] [1 5 8 6 0]
total move: 4.0
this move: 4.0
[4] [4]
total move: 6.0
this move: -2.0
[1 7] [6 6 0]
len_1_done_done!
len_1_done_done!
total move: 9.0
this move: -3.0
[4] [4]
total move: 11.0
this move: 2.0
[4] [8 0]
len_1_done_done!
len_1_done_done!
len_1_done_done!
len_1_done_done!
len_1_done_done!
total move: 15.0
this move: 4.0
[4] [4]
15.0 [array([4]), array([4]), array([4]), array([4]), array([4]), array([4]), array([4])]


(15.0,
 [array([4]),
  array([4]),
  array([4]),
  array([4]),
  array([4]),
  array([4]),
  array([4])])